version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  consumer:
    image: my-consumer:latest
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
      - "2002:4567"
    volumes:
      - /app/node_modules # use local version of node_modules directory
      - ./consumer:/app # map required directory of host inside /app directory of the container
    depends_on:
      - kafka
      - mongodb
  producer:
    image: my-producer:latest
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "2001:4567"
    volumes:
      - /app/node_modules # use local version of node_modules directory
      - ./producer:/app # map required directory of host inside /app directory of the container
    depends_on:
      - kafka
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - 'mongo_data:/data/db'
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongo_data:
    driver: local
